In [1]:
a = [1]
print(a[:-1])

[]


In [3]:
list = [1,2,3,4,5]
print(len(list))
for i in range(len(list)):
    print("this is f1 {}, f1+1={}".format(i, i+1))
    print(f"this is f2 {i}")
    print("this is f3 %d" % i)

5
this is f1 0, f1+1=1
this is f2 0
this is f3 0
this is f1 1, f1+1=2
this is f2 1
this is f3 1
this is f1 2, f1+1=3
this is f2 2
this is f3 2
this is f1 3, f1+1=4
this is f2 3
this is f3 3
this is f1 4, f1+1=5
this is f2 4
this is f3 4


In [ ]:
"""
在 print() 函数中设置 end 参数：
默认情况下，end='\n'，表示输出后换行。如果将其设置为其他值，就可以改变输出后的行为。
例如，设置 end='' 表示输出后不换行。
"""
# 输出：2、3、4, 步长为1
for i in range(2, 5):
    print("this is example %d->" % i, end = "")
    
print()

# 输出：1、3、5、7、9，步长2
for i in range(1, 10, 2):
    print(i)

切片操作

一开始只有[start, stop)

当start或stop超出上文提到的有效索引范围​时，切片操作不会抛出异常，而是进行截断。可以这样去理解截断机制：我们假象把索引范围扩充到全体整数，只不过小于​或大于​的区域对应空元素，在这个扩充后的数轴上进行切片，只需把最终结果中的所有空元素忽略即可。

In [ ]:
sub = list(range(10))
#[start:stop) stop闭区间, 左闭右开
print(sub[:5])
print(sub[5:])
print(sub[2:8])
#下标可以为负数，取负数
print(sub[-1])
print(sub[-10])
print(sub[-5:9])
print(sub[-100:9])

早期的Python解释器仅支持上述a[start:stop]形式的基本切片，后来加入了下面要介绍的切片形式，扩展切片的名称也流传下来.

扩展切片指的是这样的切片形式：a[start:stop:step]，从start对应的位置出发，以step(非0)为步长索引序列，越过stop对应的位置，且不包括stop本身

直至。事实上，简单切片就是step=1的扩展切片的特殊情况。需要详细解释的是step分别为正数和负数的两种情况。

当step为负数时，切片将其解释为从start出发以步长|step|逆序索引序列，

start->            
stop<-

此时，start和stop的截断依然遵循前述规则，但缺省发生一点变化，按照扩充索引范围的观点，start的缺省值是无穷大(​)，stop的缺省值是无穷小(​)

因为我们说过，在缺省的情况下，Python的行为是尽可能取最大区间，此时访问是逆序的，start应尽量取大，stop应尽量取小，才能保证区间最大，因此：

In [ ]:
#step为正数
print(sub)
print("step为正数:")
#省略start\stop
print(sub[::2])
print(sub[:-2:2])
print(sub[4::2])
print("step为负数:")
print(sub[5::-1])
print(sub[:4:-2])
print(sub[::-1])

#配合其他函数组合使用
print(min(sub[3::-1]))
print(max(sub[1:]))

In [ ]:
from datetime import datetime
current_time = datetime.now()
formatted_time = current_time.strftime('%Y%m%d%H%M')
print(formatted_time)
first = f"{formatted_time}-1.pdf"
print(first)

# 泊松分布

In [4]:
from scipy.stats import poisson

lambda_value = 3
k_value = 5

probability = poisson.pmf(k_value, lambda_value)
print(f'{probability * 100:.3f}%')

10.082%


In [6]:
import numpy as np
a1 = [0,1,2,3,4]
t = np.hstack(a1[1:4])
another = a1[1:4]
print(len(t))
print(another)

# 创建二维数组
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

3
[1, 2, 3]
[[1 2 3]
 [4 5 6]]


In [16]:
# 创建一个从 0 到 11 的一维数组，然后重塑为 3 行 4 列的二维数组
arr1 = np.arange(12).reshape(3, 4)  
print(arr1)
print(np.hstack(arr1[0:2]))

# d = np.array([[1, 2], [3, 4]])
# e = np.array([[5, 6], [7, 8]])
# f = np.hstack((d, e))
# print(f)
# [[1 2 5 6]
#  [3 4 7 8]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3 4 5 6 7]
